name: Cache CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache
          key: cache-49e0e3a

      - name: prime-cache-49e0e3a
        run: |
          echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
